### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by ReShout876** [danielkrupinski/Osiris#3829]
I updated the cheat, crashes upon injecting. I **tried** to debug (I didnt do this in a long time), and I got this
```
Thread 1 "csgo_linux64" received signal SIGSEGV, Segmentation fault.
0x00007fd83f6e137e in inventory_changer::game_integration::Items::getStickers(Interfaces const&, inventory_changer::game_items::Storage&) [clone .constprop.0] () from /home/reshout/Osiris/Release/libOsiris.so
```
![image](https://user-images.githubusercontent.com/63971777/197330763-598a92ff-c13e-42c1-b524-054fb95b8168.png)  
waiting for a fix :pray:   

Edit:  
been asked to `show the backtrace`
```
#0  0x00007ff2e86fb37e in inventory_changer::game_integration::Items::getStickers(Interfaces const&, inventory_changer::game_items::Storage&) [clone .constprop.0] () from /home/reshout/Osiris/Release/libOsiris.so
#1  0x00007ff2e87014a3 in inventory_changer::game_integration::createGameItemStorage(Interfaces const&, inventory_changer::game_integration::Items&) [clone .constprop.0] () from /home/reshout/Osiris/Release/libOsiris.so
#2  0x00007ff2e86f7d5a in inventory_changer::createInventoryChanger(Interfaces const&, Memory const&) [clone .constprop.0] () from /home/reshout/Osiris/Release/libOsiris.so
#3  0x00007ff2e86facea in inventory_changer::InventoryChanger::instance(Interfaces const&, Memory const&) [clone .constprop.0] () from /home/reshout/Osiris/Release/libOsiris.so
#4  0x00007ff2e8685516 in frameStageNotify(void*, csgo::FrameStage) [clone .lto_priv.0] ()
   from /home/reshout/Osiris/Release/libOsiris.so
#5  0x00007ff30b724cff in ?? ()
   from /home/reshout/Games/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#6  0x00007ff30b720bf2 in ?? ()
   from /home/reshout/Games/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#7  0x00007ff30b720d1a in ?? ()
   from /home/reshout/Games/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#8  0x00007ff30b916279 in ?? ()
   from /home/reshout/Games/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#9  0x00007ff30b72288c in ?? ()
   from /home/reshout/Games/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#10 0x00007ff32e839d59 in ?? ()
#11 0x00007ffe662b8bf0 in ?? ()
#12 0x0000000000000001 in ?? ()
#13 0x00007ffe662b8bb0 in ?? ()
#14 0x00007ff32e839d59 in ?? ()
#15 0x00007ffe662b8cc0 in ?? ()
#16 0x00007ffe662b8bf0 in ?? ()
```  
![image](https://user-images.githubusercontent.com/63971777/197332529-5c48e8bc-e704-422d-8325-3aff8296d5ef.png)

**Comment by boofiboi** [comment]
Seems like the cheat is crashing while the inventory changer scans for stickers, could be a simple fix?

**Comment by ReShout876** [comment]
It could be, now we just have to wait for @danielkrupinski to fix.
